perf: tokenize input and operate on analyzed array
chalk/slice-ansi pull request #38
Opened 2023-03-20 21:54 UTC by AlCalzone

This PR is an alternative to https://github.com/chalk/slice-ansi/pull/37

It basically rewrites the entire library, but yields a higher performance (+149% throughput, and more when reusing some of the work for slicing the same string multiple times). For my methodology on testing the performance, see #37. Some of the improvements are also taken from there.

2023-03-20 21:58 UTC, AlCalzone commented on test.js
> +	t.is(sliceAnsi('\u001B[1m\u001B[48;2;255;255;255m\u001B[38;2;255;0;0municorn\u001B[39m\u001B[49m\u001B[22m', 0, 3), '\u001B[1m\u001B[48;2;255;255;255m\u001B[38;2;255;0;0muni\u001B[39m\u001B[49m\u001
after this change, the start codes get undone in the same order as in the input string.

2023-03-20 21:58 UTC, AlCalzone commented on test.js
> +	t.is(JSON.stringify(sliceAnsi('\u001B[31m' + output, 0, 4)), JSON.stringify(chalk.black.bgYellow(' RUN')));
The ANSI code for yellow is unnecessary in the output, because it immediately gets overwritten with black

2023-03-24 08:34 UTC, sindresorhus requested changes

2023-03-24 08:34 UTC, sindresorhus commented on index.js
> +		if (charCode >= 48 && charCode <= 57) {
Magic numbers. Either add a comment about them or move them to be constants with a descriptive name.

2023-03-24 08:34 UTC, sindresorhus commented on index.js
> +			type: 'char',
```suggestion
			type: 'character',
```

2023-03-24 08:34 UTC, sindresorhus commented on index.js
> +		const fullWidth = isFullwidthCodePoint(codePoint);
```suggestion
		const isFullWidth = isFullwidthCodePoint(codePoint);
```

2023-03-24 08:34 UTC, sindresorhus commented on index.js
> +	let pos = 0;
```suggestion
	let position = 0;
```

2023-03-24 12:46 UTC, merged

2023-03-24 12:46 UTC, sindresorhus commented
Thanks :)

2023-03-24 12:54 UTC, sindresorhus commented
https://github.com/chalk/slice-ansi/releases/tag/v6.0.0